[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/podcast"
  to = "/pages/podcast"
  status = 200
